### ISSUE TITLE
scenarios needed to clarify examples

### ISSUE THREAD

**Issue by mohsenuss91** [cherifGsoul/decouple-framwork-workshop#5]
**Event storming** or user stories  needed to clarify examples.
[diagrams.net](https://app.diagrams.net) is a great tool that can be used.

![Event Storming example](https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Event_Storming_example_process.jpg/1200px-Event_Storming_example_process.jpg)

**Comment by cherifGsoul** [comment]
It is a great suggestion but it is out of the scope of the workshop.
Maybe we need it when we do a full Behavior-Driven Development session.
